{
  "language": "android",
  "jdk": "oraclejdk8",
  "android": {
    "components": [
      "tools",
      "android-$EMULATOR_API",
      "platform-tools",
      "tools",
      "build-tools-$ANDROID_BUILD_TOOLS",
      "android-$ANDROID_API",
      "extra-android-support",
      "extra-android-m2repository",
      "extra-google-m2repository",
      "sys-img-armeabi-v7a-android-$EMULATOR_API"
    ],
    "licenses": [
      ".+"
    ]
  },
  "before_script": [
  - echo no | android create avd --force -n test -t "android-26" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  ],
  "script": [
        - ./gradlew clean
        - ./gradlew assembleDebug
        - ./gradlew assembleDebugAndroidTest
  ],
  "cache": {
    "directories": [
      "$HOME/.m2",
      "$HOME/.gradle/caches/",
      "$HOME/.gradle/wrapper/",
      "$HOME/.android/build-cache"
    ]
  },
  "before_install": [
          - mkdir "$ANDROID_HOME/licenses" || true
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          - chmod +x gradlew
  ],
  "global_env": "ANDROID_API=27 
                EMULATOR_API=24 
                ANDROID_BUILD_TOOLS=27.0.2",

}